name: build-survey
on:
  push:
    tags:
        - "v*"
jobs:
  run:
    name: build-survey
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Checkout common
      uses: actions/checkout@v3
      with:
        repository: 'influenzanet/common-study-definition'
        path: 'common-study-definition'
    - name: Set Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: npm
    - name: Install deps
      run: yarn
    - name: Link
      run: ln -s common-study-definition/src common
    - name: build library
      run: yarn build
    - name: export surveys
      run: yarn grippenet
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - run: pip install influenzanet.surveys
    - name: build html
      run: python scripts/build-html.py
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          output/grippenet/surveys/*.json
          output/grippenet/surveys/*.html
          output/grippenet/studyRules.json


